"""empty message

Revision ID: 71524e7aa005
Revises: 0a22e4426123
Create Date: 2021-01-14 16:31:28.829513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71524e7aa005'
down_revision = '0a22e4426123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'about_me', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'about_me', type_='unique')
    # ### end Alembic commands ###
